### ISSUE TITLE
Something about the version of tensorflow

### ISSUE THREAD

**Issue by zhaobingbingbing** [hiveml/tensorflow-grad-cam#3]
I like your work very much,but there are somethings bother me,I used tensorflow1.3 for long time,but I noticed your work is based on tensorflow1.5, I try to run your work on  tensorflow1.3,but an error occurred,"reduce_mean() got an unexpected keyword argument 'keepdims",I think that is because the version of tensorflow, so  I have to run the program  on tensorflow1.5? If I update CUDA9.0,my tensorflow1.3 won't work,So are there programs run on lower version of tensorflow? I am very glad for your reply.

**Comment by ryanjay0** [comment]
If you change it to keep_dims it should resolve that error. Re-open this issue if you have more errors converting it to tensorflow 1.3.
